# Generated by Django 3.2 on 2021-04-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_goods',
            field=models.ManyToManyField(blank=True, related_name='goods_of_category', to='goods.Good'),
        ),
    ]
