# Generated by Django 3.2 on 2021-04-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(related_name='goods', to='goods.Category'),
        ),
    ]
