# Generated by Django 3.2 on 2021-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_category_category_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_goods',
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(to='goods.Category'),
        ),
    ]
